name: CI

on:
  push:
    branches: [ develop ]

  pull_request:
    types: [ opened, synchronize, edited ]
    
  workflow_dispatch:

jobs:
  CI:
    uses: fedandburk/workflows/.github/workflows/dotnet-ci.yml@main
    secrets: inherit
