name: ci

on:
  push:
    branches: [ develop ]

  pull_request:
    types: [ opened, synchronize, edited ]
    
  workflow_dispatch:

jobs:

  ci:
  
    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    - name: Scan
      uses: JetBrains/qodana-action@main
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

    - name: Build
      run: dotnet build --configuration Release
